from .applicant_details import ApplicantDetails
from .ownership_type import OwnershipType
from .branch import Branch
from .dealer import Dealer
from .lenders import Lender
from .loan_details import LoanDetails
from .payment_details import PaymentDetails
from .repayment_status import RepaymentStatus
from .user import User
from .comments import Comments
from .calling import Calling
from .calling_status import CallingStatus
from .co_applicant import CoApplicant
from .guarantor import Guarantor
from .applicant_references import ApplicantReferences
from .audit_applicant_details import AuditApplicantDetails
from .audit_payment_details import AuditPaymentDetails
from .vehicle_status import VehicleStatus 